import type {OrderType} from "./types";

const product11 = "/images/products/product-1(1).png";
const product2 = "/images/products/product-2.png";
const product3 = "/images/products/product-3.png";
const product4 = "/images/products/product-4.png";
const product5 = "/images/products/product-5.png";
const product6 = "/images/products/product-6.png";
const product12 = "/images/products/product-1(2).png";
const product13 = "/images/products/product-1(3).png";

export const orderList: OrderType = {
    header: ['Order ID.', 'Date', 'Product', 'Customer Name', 'Email ID', 'Phone No.', 'Address', 'Payment Type', 'Status'],
    body: [
        {
            orderID: 'RB5625',
            date: '23/07/2021',
            image: product11,
            name: 'Anna M. Hines',
            email: 'anna.hines@mail.com',
            phone: '(+1)-555-1564-261',
            address: 'Burr Ridge/Illinois',
            paymentType: 'Credit Card',
            status: 'completed',
        },
        {
            orderID: 'RB0025',
            date: '06/09/2018',
            image: product2,
            name: 'Candice F. Gilmore',
            email: 'candice.gilmore@mail.com',
            phone: '(+257)-755-5532-588',
            address: 'Roselle/Illinois',
            paymentType: 'Credit Card',
            status: 'processing',
        },
        {
            orderID: 'RB9064',
            date: '12/07/2019',
            image: product3,
            name: 'Vanessa R. Davis',
            email: 'vanessa.davis@mail.com',
            phone: '(+1)-441-5558-183',
            address: 'Wann/Oklahoma',
            paymentType: 'Pay Pal',
            status: 'cancel',
        },
        {
            orderID: 'RB9652',
            date: '31/12/2021',
            image: product4,
            name: 'Judith H. Fritsche',
            email: 'judith.fritsche.com',
            phone: '(+57)-305-5579-759',
            address: 'SULLIVAN/Kentucky',
            paymentType: 'Credit Card',
            status: 'completed',
        },
        {
            orderID: 'RB5984',
            date: '01/05/2018',
            image: product5,
            name: 'Peter T. Smith',
            email: 'peter.smith@mail.com',
            phone: '(+33)-655-5187-93',
            address: 'Yreka/California',
            paymentType: 'Pay Pal',
            status: 'completed',
        },
        {
            orderID: 'RB3625',
            date: '12/06/2020',
            image: product6,
            name: 'Emmanuel J. Delcid',
            email: 'emmanuel.delicid@mail.com',
            phone: '(+30)-693-5553-637',
            address: 'Atlanta/Georgia',
            paymentType: 'Pay Pal',
            status: 'processing',
        },
        {
            orderID: 'RB8652',
            date: '14/08/2017',
            image: product12,
            name: 'William J. Cook',
            email: 'william.cook@mail.com',
            phone: '(+91)-855-5446-150',
            address: 'Rosenberg/Texas',
            paymentType: 'Credit Card',
            status: 'processing',
        },
        {
            orderID: 'RB1002',
            date: '13/07/2018',
            image: product13,
            name: 'Martin R. Peters',
            email: 'martin.peters@mail.com',
            phone: '(+61)-455-5943-13',
            address: 'Youngstown/Ohio',
            paymentType: 'Credit Card',
            status: 'cancel',
        },
        {
            orderID: 'RB9622',
            date: '18/11/2019',
            image: product3,
            name: 'Paul M. Schubert',
            email: 'paul.schubert@mail.com',
            phone: '(+61)-035-5531-64',
            address: 'Austin/Texas',
            paymentType: 'Google Pay',
            status: 'completed',
        },
        {
            orderID: 'RB8745',
            date: '07/03/2019',
            image: product4,
            name: 'Janet J. Champine',
            email: 'janet.champine@mail.com',
            phone: '(+880)-115-5592-916',
            address: 'Nashville/Tennessee',
            paymentType: 'Google Pay',
            status: 'processing',
        },
    ],
};
